import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { DealerProvider } from "./context/delaercontext";
import { DealerItemProvider } from "./context/dealeritem";
import { LoginUserProvider } from "./context/loginuser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <LoginUserProvider>
          <DealerProvider>
            <DealerItemProvider>
              {children}
            </DealerItemProvider>
          </DealerProvider>
        </LoginUserProvider>

      </body>
    </html>
  );
}
